# Change these first
owner: fmrtso # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: bnApp / bnMobMonteur
    url: $STATUSPAGE_BNAPP
  - name: bnInfocenter.de / mobiler Monteur Classic
    url: $STATUSPAGE_BNINFOCENTERDE

status-website:
  cname: status.kwp-online.de
  logoUrl: https://www.kwpsoftware.de/wp-content/uploads/2019/02/hp-kwp-logo-lang-284px.png
  name: ""
  introTitle: 
  introMessage: 
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: Aktuelle Vorfälle
  allSystemsOperational: Keine Einschränkungen
  incidentReport: "Vorfall #$NUMBER report →"
  activeIncidentSummary: Geöffnet am $DATE
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Details
  incidentFixed: Behoben
  incidentOngoing: in Bearbeitung
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Behoben in $MINUTES Minuten
  liveStatus: Live Status
  overallUptime: "Verfügbarkeit: $UPTIME"
  overallUptimeTitle: "Verfügbarkeit"
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: "Durchschnittliche Antwortzeit" #Average response
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Antwortzeit (ms)
  up: Verfügbar
  down: Nicht verfügbar
  degraded: Eingeschränkt
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: "" # This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Vergangene Wartung
  scheduledMaintenance: Geplante Wartung
  scheduledMaintenanceSummaryStarted: Begann am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Begann am
  startsAt: Beginnt am
  duration: Dauer
  durationMin: $DURATION minutes
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: Alles
